### ISSUE TITLE
bug - preserve derive dependencies when Oven rebuilds provider child modules

### ISSUE THREAD

**Issue by dannymeijer** [encero-systems/incan#1467]
## Area

Compiler (frontend/backend/codegen)

## Summary

A source-backed provider can bake successfully yet fail when a function-only consumer rebuilds it through Oven. The provider has a model in a child module; its root module only reexports a function. The rebuilding path omits the required `incan_derive` extern because `caller_owned_library_dependencies_without_unused_incan_derive` examines only `src/lib.rs`, while the generated derive invocation lives in `src/defs.rs`.

Expected: the consumer builds and prints `42`, retaining the provider's required procedural macro dependency through the selected native plan.

Actual: consumer bake fails with E0433 in the provider's generated child module. In the observed selected plan, the authenticated host macro binary is already present in `supporting_artifacts`; it is absent from the exposed `externs`. This is not evidence that another SDK build or warm-up is needed.

This blocks one native acceptance check for #1426 after its separate optional-union metadata fix. The reduced case below uses no unions and establishes a separate provider-rebuilding defect. No valid workaround has been established; adding an unused model to the consumer would hide the dependency error.

## Reproduction steps

Use an installed compiler with its matching prepared SDK, and two sibling projects.

`provider/loaf.toml`:

```toml
[project]
name = "derive_child_provider"
version = "0.1.0"
```

`provider/src/defs.incn`:

```incan
model Item:
    value: int

pub def answer() -> int:
    return Item(value=42).value
```

`provider/src/lib.incn`:

```incan
pub from defs import answer
```

`consumer/loaf.toml`:

```toml
[project]
name = "derive_child_consumer"
version = "0.1.0"

[dependencies]
provider = { path = "../provider" }
```

`consumer/src/main.incn`:

```incan
from pub::provider import answer

def main() -> None:
    println(answer())
```

With a fresh consumer output, run:

```sh
INCAN_OVEN_BAKE_PROFILES=debug incan oven bake --project provider
INCAN_OVEN_BAKE_PROFILES=debug incan oven bake --project consumer
```

The provider succeeds; the consumer fails during direct Rust compilation of the provider. The observed selected closure exposes only `incan_stdlib`, `incan_stdlib_core` and the provider, although it retains the verified host `incan_derive` binary as a supporting artifact. Selection must preserve exact typed dependency and artifact authority; selecting an arbitrary matching filename is insufficient.

## Output / logs

```text
error[E0433]: cannot find module or crate `incan_derive` in this scope
 --> provider/target/lib/src/defs.rs:6:24
  |
6 | #[derive(Debug, Clone, incan_derive::FieldInfo, incan_derive::IncanClass)]
  |                        ^^^^^^^^^^^^ use of unresolved module or unlinked crate `incan_derive`
```

The second derive path on the same line reports the same error. The direct-rustc invocation lacks `--extern incan_derive`.

The root-only filtering function is unchanged from [5901d991f723e03db0e6af222334ccab1bea23c2](https://github.com/encero-systems/incan/commit/5901d991f723e03db0e6af222334ccab1bea23c2), introduced by #1062 and present in `0.6.0-dev.4` at `aeef7990bed4d8c880758e39391f9f529fc9ee0a`. No fix to this function was applied for the reproduction.

## Environment

- macOS, aarch64-apple-darwin, Rust 1.98.0.
- Incan public version `0.6.0-dev.3`; development target `0.6.0-dev.4`.
- Reproduced with a local #1426 repair compiler based on `695a165b3a4814f6b360ecad6ff4a4a018fc98b6`, binary SHA-256 `db914fd838e45e1e0fcf68efdf6caf2e34bd214673b5d2ce00e23afe989b0c3e`. This is local repair evidence, not a claim that a new public PR head passed.
- Matching SDK inventory SHA-256 `c9906102d8ae1f6edfa9e6f951011c25175dd15a1446824819a1f98a75704c15`; all ten provider digests and support roots stayed unchanged across both operations.
- Complete measured windows: provider 26.862s; consumer failure 38.365s.

**Comment by dannymeijer** [comment]
Landed on `0.6.0-dev.4` through #1468. Regressions `selected_provider_macro_requirements_follow_named_roots` and `provider_macro_dependency_refuses_changed_sources_and_declarations` pass on the current dev line. Closing.
